=== errantlinguist/errantlinguist.github.io/content/cv/publications/document.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
	Licensed to the Apache Software Foundation (ASF) under one
	or more contributor license agreements.  See the NOTICE file
	distributed with this work for additional information
	regarding copyright ownership.  The ASF licenses this file
	to you under the Apache License, Version 2.0 (the
	"License"); you may not use this file except in compliance
	with the License.  You may obtain a copy of the License at

		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing,
	software distributed under the License is distributed on an
	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
	KIND, either express or implied.  See the License for the
	specific language governing permissions and limitations
	under the License.
-->
<!DOCTYPE xs:schema PUBLIC "-//W3C//DTD XMLSCHEMA 200102//EN" "http://www.w3.org/2001/XMLSchema.dtd">
<xs:schema
	targetNamespace="http://citeseerx.ist.psu.edu"
	xmlns:target="http://citeseerx.ist.psu.edu"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation xml:lang="en">
			AUTHOR: Todd Shore
			VERSION: 2013-06-24
			COPYRIGHT: Copyright 2013 Todd Shore. Licensed for distribution under the Apache License 2.0.
			WEBSITE: http://errantlinguist.com

			A schema defining an XML file which describes a document in CiteSeerX format.
		</xs:documentation>
	</xs:annotation>
	<!-- Include data source constant schema -->
	<xs:include schemaLocation="http://errantlinguist.com/content/cv/publications/sourceConstant.xsd"/>
	<!-- Include special string constants -->
	<xs:include
		schemaLocation="http://errantlinguist.com/content/cv/publications/stringConstants.xsd"/>

	<xs:element name="document" type="target:document"/>
	<xs:complexType name="document">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A CiterSeerX-compatible "document" element.
			</xs:documentation>
		</xs:annotation>
		<xs:all minOccurs="1" maxOccurs="1">
			<xs:element name="clusterid" type="xs:nonNegativeInteger" nillable="true"/>
			<xs:element name="title" type="target:tokenFromSource"/>
			<xs:element name="abstract" type="target:tokenFromSource" nillable="true"/>
			<xs:element name="year" type="target:yearFromSource"/>
			<xs:element name="venue" type="target:tokenFromSource" nillable="true"/>
			<xs:element name="venType" type="target:emptyTokenFromSource" nillable="true"/>
			<xs:element name="pages" type="target:pageRangeStringFromSource" nillable="true"/>
			<xs:element name="volume" type="target:emptyIntegerFromSource" nillable="true"/>
			<xs:element name="number" type="target:emptyIntegerFromSource" nillable="true"/>
			<xs:element name="publisher" type="target:tokenFromSource" nillable="true"/>
			<xs:element name="pubAddress" type="target:tokenFromSource" nillable="true"/>
			<xs:element name="tech" type="target:tokenFromSource" nillable="true"/>
			<xs:element name="keywords">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="keyword" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>				
					</xs:sequence>
				</xs:complexType>	
			</xs:element>
			<xs:element name="authors">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="author" type="target:author" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="citations" type="target:citationsFromSource" nillable="true"/>
			<xs:element name="fileInfo" type="target:fileInfo"/>
		</xs:all>
		<xs:attributeGroup ref="target:paperId"/>
	</xs:complexType>

	<xs:complexType name="author">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A CiterSeerX-compatible "author" element.
			</xs:documentation>
		</xs:annotation>
		<xs:all minOccurs="1" maxOccurs="1">
			<xs:element name="name" type="target:tokenFromSource"/>
			<xs:element name="affil" type="target:tokenFromSource"/>
			<xs:element name="address" type="target:tokenFromSource"/>
			<xs:element name="email" type="target:emptyTokenFromSource"/>
			<xs:element name="order" type="target:positiveIntegerFromSource"/>
		</xs:all>
		<xs:attributeGroup ref="target:authorId"/>
	</xs:complexType>

	<xs:complexType name="citation">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A CiterSeerX-compatible "citation" element.
			</xs:documentation>
		</xs:annotation>
		<xs:all minOccurs="1" maxOccurs="1">
			<xs:element name="clusterid" type="xs:nonNegativeInteger" nillable="true"/>
			<xs:element name="authors" type="xs:token"/>
			<xs:element name="title" type="xs:token" minOccurs="0" maxOccurs="1"/>
			<xs:element name="venue" type="xs:token" minOccurs="0" maxOccurs="1"/>
			<xs:element name="venType" type="xs:token" minOccurs="0" maxOccurs="1"/>
			<xs:element name="year" type="xs:gYear"/>
			<xs:element name="tech" type="xs:token" minOccurs="0" maxOccurs="1"/>
			<xs:element name="volume" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="number" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="pages" type="target:pageRangeString" minOccurs="0" maxOccurs="1"/>
			<xs:element name="editors" type="xs:token" minOccurs="0" maxOccurs="1"/>
			<xs:element name="publisher" type="xs:token" minOccurs="0" maxOccurs="1"/>
			<xs:element name="pubAddress" type="xs:token" minOccurs="0" maxOccurs="1"/>
			<xs:element name="raw" type="xs:token"/>
			<xs:element name="paperid" type="target:paperId"/>
		</xs:all>
		<xs:attributeGroup ref="target:paperId"/>
	</xs:complexType>

	<!-- <xs:complexType name="citation">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A CiterSeerX-compatible "citation" element.
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="target:abstractCitation">
					<xs:sequence>
						<xs:choice>
							<xs:element name="pages" type="target:complexPageRange"/>
							<xs:element name="pages" type="target:pageRangeString"/>
						</xs:choice>
					</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType> -->

	<xs:complexType name="citationsFromSource">
		<xs:sequence>
			<xs:element name="citation" type="target:citation" minOccurs="0" maxOccurs="unbounded"/>			
		</xs:sequence>
		<xs:attributeGroup ref="target:src"/>
	</xs:complexType>

	<!-- <xs:complexType name="complexPageRange">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A range of pages, which need not be actual numbers (e.g. they could be "A" to "B")
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
				<xs:element name="min" type="xs:token"/>
				<xs:element name="max" type="xs:token"/>			
		</xs:sequence>
	</xs:complexType> -->

	<xs:simpleType name="pageRangeString">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A string denoting a range of pages, which need not be actual numbers (e.g. they could be "A" to "B")
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[^-]+--[^-]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="authorId">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A CiterSeerX-compatible nullable author ID, e.g. for which the string "null" is an acceptable value.
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="xs:nonNegativeInteger target:nullString"/>
	</xs:simpleType>

	<xs:attributeGroup name="authorId">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				An attribute group for elements which can have a defined CiteSeerX-compatible author ID.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="id" type="target:authorId" use="required"/>
	</xs:attributeGroup>

	<xs:simpleType name="paperId">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A string denoting a paper ID, e.g. "10.1.1.14.3077".
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[\d]+(.[\d]+)*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nullablePaperId">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A string denoting a nullable paper ID, e.g. "10.1.1.14.3077" or "null".
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="target:paperId target:nullString"/>
	</xs:simpleType>

	<xs:attributeGroup name="paperId">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				An attribute group for elements which can have a defined CiteSeerX-compatible paper ID.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="id" type="target:nullablePaperId" use="required"/>
	</xs:attributeGroup>

	<xs:complexType name="fileInfo">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A CiterSeerX-compatible "fileInfo" element.
			</xs:documentation>
		</xs:annotation>
		<xs:all minOccurs="1" maxOccurs="1">
			<xs:element name="crawldate" type="xs:token" nillable="true"/>
			<xs:element name="repID" type="xs:token" nillable="true"/>
			<xs:element name="conversionTrace" type="xs:token" nillable="true"/>
			<xs:element name="urls">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="url" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>	
			</xs:element>
		</xs:all>	
	</xs:complexType>

	<xs:simpleType name="source">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				The source of a given datum.
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="xs:token target:sourceConstant"/>
	</xs:simpleType>

	<xs:attributeGroup name="src">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				An attribute group for elements which can have a defined source.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="src" type="xs:token" use="required"/>
	</xs:attributeGroup>

	<!-- <xs:complexType name="xhtml">
		<xs:complexContent mixed="true">
			<xs:restriction base="xs:anyType">
				<xs:sequence>
					<xs:any processContents="lax" namespace="http://www.w3.org/1999/xhtml" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType> -->

	<!-- Definition of integer which is able to have no value, e.g not even "0" -->
 	<xs:simpleType name="emptyInteger">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				An integer which is able to have no value, e.g not even "0".
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="xs:integer target:emptyString"/>
	</xs:simpleType>
	<!-- Definition of token which is able to have no value, e.g not even "0" -->
 	<xs:simpleType name="emptyToken">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				A token which is able to have no value, e.g "".
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="xs:token target:emptyString"/>
	</xs:simpleType>

	<!-- Simple XML types extended to have a defined source attribute -->
	<xs:complexType name="emptyIntegerFromSource">
		<xs:simpleContent>
			<xs:extension base="target:emptyInteger">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="positiveIntegerFromSource">
		<xs:simpleContent>
			<xs:extension base="xs:positiveInteger">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="tokenFromSource">
		<xs:simpleContent>
			<xs:extension base="xs:token">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="emptyTokenFromSource">
		<xs:simpleContent>
			<xs:extension base="target:emptyToken">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="yearFromSource">
		<xs:simpleContent>
			<xs:extension base="xs:gYear">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!-- <xs:complexType name="complexPageRangeFromSource">
		<xs:complexContent>
			<xs:extension base="target:complexPageRange">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType> -->
	<xs:complexType name="pageRangeStringFromSource">
		<xs:simpleContent>
			<xs:extension base="target:pageRangeString">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!-- <xs:complexType name="xhtmlFromSource">
		<xs:complexContent>
			<xs:extension base="target:xhtml">
				<xs:attributeGroup ref="target:src"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType> -->
</xs:schema>

=== errantlinguist/errantlinguist.github.io/content/cv/publications/rescoring.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://errantlinguist.com/content/cv/publications/document.xsl"?>
<csx:document
	xmlns:csx="http://citeseerx.ist.psu.edu"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://citeseerx.ist.psu.edu http://errantlinguist.com/content/cv/publications/document.xsd"
	id="null">
	<clusterid xsi:nil="true"/>
	<title src="user correction">Knowledge-Based Word Lattice Rescoring in a Dynamic Context</title>
	<abstract src="user correction">Recent advances in automatic speech recognition (ASR) technology continue to be based heavily on data-driven methods, meaning that the full benefits of such research are often not enjoyed in domains for which there is little training data available. Moreover, tractability is often an issue with these methods when conditioning for long-distance dependencies, entailing that many higher-level knowledge sources such as situational knowledge cannot be easily utilized in classification. This paper describes an effort to circumvent this problem by using dynamic contextual knowledge to rescore ASR lattice output using a dynamic weighted constraint satisfaction function. With this method, it was possible to achieve a roughly 80% reduction in WER for ASR in the context of an air traffic control scenario.</abstract>
	<year src="user correction">2012</year>
	<venue src="user correction">Proceedings of the 13th Annual Conference of the International Speech Communication Association (InterSpeech 2012)</venue>
	<venType src="user correction">CONFERENCE</venType>
<!--	<pages src="user correction">
		<min>1083</min>
		<max>1086</max>
	</pages> -->
	<pages src="user correction">1083--1086</pages>
	<volume src="user correction"></volume>
	<number src="user correction"></number>
	<publisher src="user correction">International Speech Communication Association</publisher>
	<pubAddress src="user correction">Portland, OR, USA</pubAddress>
	<tech src="user correction"></tech>
	<keywords>
		<keyword>lattice rescoring</keyword>
		<keyword>knowledge-based</keyword>
		<keyword>context-sensitivity</keyword>
	</keywords>
	<authors>
		<author id="null">
			<name src="user correction">Todd Shore</name>
			<affil src="user correction">Spoken Language Systems, Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction">todd.shore@lsv.uni-saarland.de</email>
			<order src="user correction">1</order>
		</author>
		<author id="null">
			<name src="user correction">Friedrich Faubel</name>
			<affil src="user correction">Spoken Language Systems, Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction">friedrich.faubel@lsv.uni-saarland.de</email>
			<order src="user correction">2</order>
		</author>
		<author id="null">
			<name src="user correction">Hartmut Helmke</name>
			<affil src="user correction">Institute for Flight Guidance, German Aerospace Center (DLR)</affil>
			<address src="user correction">Braunschweig, Germany</address>
			<email src="user correction">hartmut.helmke@dlr.de</email>
			<order src="user correction">3</order>
		</author>
		<author id="null">
			<name src="user correction">Dietrich Klakow</name>
			<affil src="user correction">Spoken Language Systems, Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction">dietrich.klakow@lsv.uni-saarland.de</email>
			<order src="user correction">4</order>
		</author>
	</authors>
	<citations src="user correction" xsi:nil="true"/>
	<fileInfo>
		<crawldate xsi:nil="true"/>
		<repID xsi:nil="true"/>
		<conversionTrace xsi:nil="true"/>
		<urls>
			<url>http://www.isca-speech.org/archive/interspeech_2012/i12_1083.html</url>
		</urls>
	</fileInfo>
</csx:document>

=== errantlinguist/errantlinguist.github.io/content/cv/publications/verb-aspect.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://errantlinguist.com/content/cv/publications/document.xsl"?>
<csx:document
	xmlns:csx="http://citeseerx.ist.psu.edu"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://citeseerx.ist.psu.edu http://errantlinguist.com/content/cv/publications/document.xsd"
	id="null">
	<clusterid xsi:nil="true"/>
	<title src="user correction">Psycholinguistic Experiments on Verb Aspect and Causality</title>
	<abstract>Verb aspect has been found to be an important factor when building up a situational model of events (Ferretti et al., 2009, Madden &amp; Zwaan, 2003). However, it is not clear yet, how verb aspect interacts with other properties of events, such as causality. This interaction between Verb Aspect and Causal Agents is the main interest of our study. In order to investigate both the final representation of the situation and the online processes in which the two kinds of information are integrated, we used two tasks: an online completion task and an online self paced reading task. Our experiments: Experiment 1 (completion task) and 2 (self-paced reading task) establish the Aspect effects on comprehension and Experiment 3 (completion task) and 4 (self-paced reading task) aim in revealing the interaction of Aspect and Causality. In the stimuli for Experiment 1, (example: "Während/Als Jan Franziska einen Ball gab, wollte..."), the "Während" stands for the imperfective condition and the "Als" for the perfective aspect. By using transfer of possession verbs the participant can focus on the process (imperfective), where he would complete the sentence referring back to the subject (NP1) or on the end phase of the event (perfective condition), in which he is expected to continue the sentence with an NP2 (second sentence participant) back reference.The same setup for the second set of experiments, which also involve causality, include stimuli as the following: "Während/Als Stefan Caroline nach Hause brachte, wollte...". We used causal movement verbs to attribute Causality to the Agent (Dowty, 1991) and study how its bias towards the Agent interacts with the Aspect bias (perfective aspect and causality clash, imperfective aspect and causality favor the same noun phrase). For the respective online experiments (Experiment 2 and 4), we added continuations, which were either congruent or incongruent with the biases of the factors and measured response times. The online results point to a general bias towards coreference, as opposed to introducing a new entity, but no clear tendency for a specific participant (NP1 or NP2). Also, the effect of Agent Causality appears to be strengthened in the case of the perfective aspect, where both factors favor the same participant. The online results are currently studied in detail, updates will be included in the talk.</abstract>
	<year src="user correction">2010</year>
	<venue src="user correction">48. Studentische Tagung der Sprachwissenschaft (STuTS 2010)</venue>
	<venType src="user correction">CONFERENCE</venType>
	<pages src="user correction">2--18</pages>
	<volume src="user correction"></volume>
	<number src="user correction"></number>
	<publisher src="user correction"></publisher>
	<pubAddress src="user correction">Potsdam, Germany</pubAddress>
	<tech src="user correction"></tech>
	<keywords></keywords>
	<authors>
		<author>
			<name src="user correction">Katerina Danae Kandylaki</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction">aikater@coli.uni-sb.de</email>
			<order src="user correction">1</order>
		</author>
		<author>
			<name src="user correction">Casey Redd Kennington</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction"></email>
			<order src="user correction">2</order>
		</author>		
		<author>
			<name src="user correction">Florian Niefind</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction"></email>
			<order src="user correction">3</order>
		</author>
		<author>
			<name src="user correction">Andreas Rebmann</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction"></email>
			<order src="user correction">4</order>
		</author>
		<author>
			<name src="user correction">Todd Shore</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction"></email>
			<order src="user correction">5</order>
		</author>
		<author>
			<name src="user correction">Pirita Pyykkönen</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">Saarbrücken, Germany</address>
			<email src="user correction"></email>
			<order src="user correction">6</order>
		</author>		
	</authors>
	<fileInfo>
		<crawldate xsi:nil="true"/>
		<repID xsi:nil="true"/>
		<conversionTrace xsi:nil="true"/>
		<urls>
			<url>http://48.stuts.eu/files/Kandylaki_Aspect&amp;Causality.pdf</url>
		</urls>
	</fileInfo>
</csx:document>

=== errantlinguist/errantlinguist.github.io/content/cv/publications/associative-adjectives.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://errantlinguist.com/content/cv/publications/document.xsl"?>
<csx:document
	xmlns:csx="http://citeseerx.ist.psu.edu"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://citeseerx.ist.psu.edu http://errantlinguist.com/content/cv/publications/document.xsd"
	id="null">
	<clusterid xsi:nil="true"/>
	<title src="user correction">Information Retrieval and Visualization for the Historical Domain</title>
	<abstract src="user correction">Associative adjectives such as in electrical engineer differ from ascriptive adjectives like in red house: They are syntactically similar, yet they do not denote an intersective  sense like ascriptive adjectives do. However, associative adjectives may (irregularly) denote ascriptive traits connected to the associated entity: The more semanticallysimilar two entities are, the more regular the traits are which are ascribed to them through association by a given adjective. This model of entities associated through family membership is analogous to a semantic network based on relative word similarities, in which families appear as clusters of relatively-similar entities.</abstract>
	<year src="user correction">2010</year>
	<venue src="user correction">SKASE Journal of Theoretical Linguistics</venue>
	<venType src="user correction">JOURNAL</venType>
	<pages src="user correction">2--18</pages>
	<volume src="user correction">7</volume>
	<number src="user correction">3</number>
	<publisher src="user correction">Slovak Association for the Study of English</publisher>
	<pubAddress src="user correction"></pubAddress>
	<tech src="user correction"></tech>
	<keywords>
		<keyword>lexical semantics</keyword>
		<keyword>adjectives</keyword>
		<keyword>modification</keyword>
		<keyword>predication</keyword>
		<keyword>similarity</keyword>
		<keyword>family resemblance</keyword>
		<keyword>ontology</keyword>
	</keywords>
	<authors>
		<author>
			<name src="user correction">Todd Shore</name>
			<affil src="user correction">Department of Computational Linguistics and Phonetics, Saarland University</affil>
			<address src="user correction">Buildings C7.1, C7.2 &amp; C7.4, 66041 Saarbr√ºcken, Germany</address>
			<email src="user correction">todd.shore@coli.uni-saarland.de</email>
			<order src="user correction">1</order>
		</author>
	</authors>
	<fileInfo>
		<crawldate xsi:nil="true"/>
		<repID xsi:nil="true"/>
		<conversionTrace xsi:nil="true"/>
		<urls>
			<url>http://www.skase.sk/Volumes/JTL17/pdf_doc/01.pdf</url>
		</urls>
	</fileInfo>
</csx:document>

=== errantlinguist/errantlinguist.github.io/content/cv/publications/historyexplorer.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://errantlinguist.com/content/cv/publications/document.xsl"?>
<csx:document
	xmlns:csx="http://citeseerx.ist.psu.edu"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://citeseerx.ist.psu.edu http://errantlinguist.com/content/cv/publications/document.xsd"
	id="null">
	<clusterid xsi:nil="true"/>
	<title src="user correction">Information Retrieval and Visualization for the Historical Domain</title>
	<abstract src="user correction">Working with large and unstructured collections of historical documents is a challenging task for historians. Despite the recent growth in the volume of digitized historical data, available collections are rarely accompanied by computational tools that significantly facilitate this task.We address this shortage by proposing a visualization method for document collections that focuses on graphical representation of similarities between documents. The strength of the similarities is measured according to the overlap of historically significant information such as named entities,or the overlap of general vocabulary. Similarity strengths are then encoded in the edges of a graph.The graph provides visual structure, revealing interpretable clusters and links between documents that are otherwise difficult to establish. We implement the idea of similarity graphs within an information retrieval system supported by an interactive graphical user interface. The system allows querying the database, visualizing the results and browsing the collection in an effective and intuitive way. Our aproach can be easy adapted and extended to collections of documents in other domains.</abstract>
	<year src="user correction">2011</year>
	<venue src="user correction">Language Technology for Cultural Heritage: Selected Papers from the LaTeCH Workshop Series</venue>
	<venType src="user correction">BOOKCHAPTER</venType>
	<pages src="user correction">197--212</pages>
	<volume src="user correction"></volume>
	<number src="user correction"></number>
	<publisher src="user correction">Springer</publisher>
	<pubAddress src="user correction"></pubAddress>
	<tech src="user correction"></tech>
	<keywords>
		<keyword>historical collections</keyword>
		<keyword>information retrieval</keyword>
		<keyword>graph visualization</keyword>
		<keyword>clustering</keyword>
		<keyword>recommender system</keyword>
	</keywords>
	<authors>
		<author id="null">
			<name src="user correction">Yevgeni Berzak</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">66041 Saarbr端cken, Germany</address>
			<email src="user correction">berzak@coli.uni-sb.de</email>
			<order src="user correction">1</order>
		</author>
		<author id="null">
			<name src="user correction">Michal Richter</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">66041 Saarbr端cken, Germany</address>
			<email src="user correction">mrichter@mpi-inf.mpg.de</email>
			<order src="user correction">2</order>
		</author>
		<author id="null">
			<name src="user correction">Carsten Ehrler</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">66041 Saarbr端cken, Germany</address>
			<email src="user correction">carsten.ehrler@gmail.com</email>
			<order src="user correction">3</order>
		<author id="null">
			<name src="user correction">Todd Shore</name>
			<affil src="user correction">Saarland University</affil>
			<address src="user correction">66041 Saarbr端cken, Germany</address>
			<email src="user correction">todd.shore@coli.uni-saarland.de</email>
			<order src="user correction">4</order>
		</author>
		</author>
	</authors>
	<fileInfo>
		<crawldate xsi:nil="true"/>
		<repID xsi:nil="true"/>
		<conversionTrace xsi:nil="true"/>
		<urls>
			<url>http://dx.doi.org/10.1007/978-3-642-20227-8_11</url>
		</urls>
	</fileInfo>
</csx:document>
